### ISSUE TITLE
Can't implement version 2.2.0

### ISSUE THREAD

**Issue by andrey-timofeev** [SumSubstance/KYC-Android-Release#2]
Dependencies (implementation 'com.sumsub:kyc-liveness3d:2.2.0'
implementation 'com.sumsub:kyc-client:2.2.0' ) throw ERROR: Failed to resolve: com.facetec:zoom-authentication-hybrid:7.0.14. Do you can help me?

**Comment by Djangist** [comment]
Please use latest version of the library (2.3.2)

**Comment by SungjunApp** [comment]
I've experienced the problem on ver 2.2.0 as well. So, I went back to using the file library. 

Has the problem been fixed on the version 2.3.2?

**Comment by andrey-timofeev** [comment]
@SungjunApp me help update to 2.3.1

**Comment by Djangist** [comment]
@SungjunApp Did you try 2.3.2 version?

**Comment by SungjunApp** [comment]
@Djangist I started to try 2.3.2 since yesterday. It works fine on the testing server. However on live server it keep crashing showing the message : issue #4
