### ISSUE TITLE
Support AndroidX

### ISSUE THREAD

**Issue by andrey-timofeev** [SumSubstance/KYC-Android-Release#3]
Can't integrate version 2.3.0 with andoidX

**Comment by Djangist** [comment]
@BuddyJava Can you share error messages or any additional information about the problem?

**Comment by Djangist** [comment]
Soon, we release an alternative version with androidx support. It's already done but needs more testing.

**Comment by andrey-timofeev** [comment]
@Djangist R8 cant't transform talkheads.plugin, but version 2.3.1 compiled. Issue closed
