### ISSUE TITLE
Start taking a photo of Password leads to a crash showing this error below

### ISSUE THREAD

**Issue by SungjunApp** [SumSubstance/KYC-Android-Release#4]
Process: com.bluewhale.sa.stg, PID: 5988
    java.lang.RuntimeException: Bad input YUV data format
        at biz.smartengines.smartid.swig.jniSmartIdEngineJNI.RecognitionSession_ProcessYUVSnapshot__SWIG_2(Native Method)
        at biz.smartengines.smartid.swig.RecognitionSession.ProcessYUVSnapshot(RecognitionSession.java:78)
        at com.sumsub.kyc.client.ui.file.camera.PhotoCaptureViewModel$3.run(PhotoCaptureViewModel.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by SungjunApp** [comment]
Some how now it does not crash any more although I did not change any thing.

**Comment by Djangist** [comment]
@SungjunApp Hmm, maybe Gradle cache or something of floating issues.
Can you share code for SDK launch? We will check it.
Also, check please camera settings. Maybe it was an incorrect photo format or something similar.

**Comment by SungjunApp** [comment]
This is the code I use when launching KYCChatActivity.java

**Comment by SungjunApp** [comment]
@Djangist 
This is the code I use for launching KYCChatActivity

```
fun startKycamlChat(context: Context, applicantId: String, baseViewModel: BaseAuthViewModel) {
        val clientData = KYCClientData(
            "msdk.sumsub.com",
            "com.bluewhale.sa",
            "0.7.1",
            Locale("en", "UK"),
            applicantId,
            AppConfig.kycamlSupportEmail,
            KYCColorConfig(),
            KYCStringConfig(),
            KYCIconConfig()
        )

        KYCManager.init(context, clientData,
            object : KYCTokenUpdater {
                override fun getInitialToken(callback: ParamCallback<String>) {
                    callback?.onResult(baseViewModel.getKycamlAccessToken())
                }

                override fun updateExpiredToken(
                    expiredToken: String,
                    callback: ParamCallback<String>
                ) {
                    baseViewModel.getAccessToken(false, expiredToken, callback)
                }
            },
            listOf(Liveness3DModule())
        )
        val intent = Intent(context, KYCChatActivity::class.java)
        startActivityForResult(intent, KYC_REQUEST_CODE)
    }
```

**Comment by SungjunApp** [comment]
@Djangist This only happens when I use 'msdk.sumsub.com'. The app using 'test-msdk.sumsub.com' works fine. 'msdk.sumsub.com' is for the production environment.

**Comment by SungjunApp** [comment]
@Djangist I found the cause for this. 'msdk.sumbsub.com' has nothing to do with the crash. 

After I generate with app signing, launching MobileSDK leads to crashing. Any Idea?

**Comment by Djangist** [comment]
@SungjunApp 
We will check it. Maybe something with Proguard rules if you are using it.

**Comment by Djangist** [comment]
@SungjunApp
Fixed. Please try 2.3.5 SDK version.
