### ISSUE TITLE
Infinity loading

### ISSUE THREAD

**Issue by andrey-timofeev** [SumSubstance/KYC-Android-Release#5]
For some users are showing progress after initialisation ChatFragment, what can it be connected with? 
Approximate problem location 

> private Observer<List<EventBaseEntity>> eventsObserver = new Observer<List<EventBaseEntity>>() {
        public void onChanged(@Nullable List<EventBaseEntity> events) {
            ChatFragment.this.chatAdapter.setData(events);
            if (events.size() > 0) {
                ChatFragment.this.hideProgress();
                ChatFragment.this.recyclerView.scrollToPosition(events.size() - 1);
            } else {
                ChatFragment.this.showProgress();
            }
        }
    };

**Comment by Djangist** [comment]
@BuddyJava What SDK version do you use? It would better to share that information.  We have often releases, so it could be fixed in the latest stable SDK version (2.5.3 now).
